title: Flative 기술 블로그
email: flative.dev@gmail.com
description: |
  Flative 기술 블로그입니다. 프로젝트를 통해 얻게되는 경험이나 생각들을 공유합니다.
keywords: 'flative 기술 블로그 기술블로그'
baseurl: 'blog'
url: 'https://flative.github.io/'

repository: flative/blog.flative.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 20
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]
keep_files: [assets, files]

author: flative.dev@gmail.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
google_analytics:
  ua: 'UA-84069358-1'
facebook:
  username: flative
twitter:
  username: TeamFlative
google_plus:
  username: flative.dev
github:
  username: flative
